### ISSUE TITLE
Group Finder Role Icons

### ISSUE THREAD

**Issue by Teng3n** [Kkthnx/ElvUI_Kkthnx_WotLK#1]
Not sure if you're still supporting this, but if you are I'd appreciate it if you could look into this issue.

When trying to create a group in the group finder role icons do not show up. As well as weird skinning on 'X' button.

![screenshot_3](https://cloud.githubusercontent.com/assets/18473227/14547033/bbd6a8e0-025e-11e6-806d-149850231e8c.png)

**Comment by Kkthnx** [comment]
Go into the interface folder and delete everything but the addons folder. DO NOT DELETE THE ADDONS FOLDER.
